before_script:
  - uname -r 

types:
  - build
  - test
  - deploy

job_test:
  type: test
  script:
    - apt-get -qq update -y  > /dev/null
    - apt-get -qq install -y libncurses5-dev > /dev/null
    - apt-get -qq install -y libxml2-dev libxslt1-dev  > /dev/null
    - apt-get -qq install -y python-dev libffi-dev libssl-dev  > /dev/null
    - apt-get -qq install -y python-virtualenv  > /dev/null
    - apt-get -qq install -y python-pip  > /dev/null
    - virtualenv --no-site-packages venv  > /dev/null
    - source venv/bin/activate
    - pip install -q -r requirements.txt
    - sed -i.bak "s/__YT_API_KEY__/$YT_API_KEY/g" crawler/crawler/settings.sample.py
    - sed -i.bak "s/__FB_APP_ID__/$FB_APP_ID/g" crawler/crawler/settings.sample.py
    - sed -i.bak "s/__FB_APP_SECRET__/$FB_APP_SECRET/g" crawler/crawler/settings.sample.py
    - cp crawler/crawler/settings.sample.py crawler/crawler/settings.py 
    - cd crawler/core
    - py.test --cov-config=.coveragerc --cov-report=xml --cov-report=term --cov=.  tests -v -s
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  only:
    - master
  tags:
    - ruby
